function isit = is_dominating_set(G,D)
%
% function isit = is_dominating_set(G,D)
%
% Check if set vertices in D are a domianting set for G
% G is a graph structure generated by the GSP toolbox (https://lts2.epfl.ch/gsp/) 

B = G.A;

s = sum(B(D,:));
s(D) = 1;

isit = (full(sum(s>0)) == G.N);